# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "FoorseeSearchTest" do

pod 'AFNetworking', '2.2.3'
pod "CSStickyHeaderFlowLayout"
pod 'FXBlurView', '~> 1.6'
pod 'AXRatingView', '~> 0.9.7'

end

target "FoorseeSearchTestTests" do

end

