# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "FoorseeSearchTest" do

pod 'AFNetworking', '2.2.3'
pod 'JTSImageViewController', '~> 1.1'
pod "CSStickyHeaderFlowLayout"
pod 'FXBlurView', '~> 1.6'


end

target "FoorseeSearchTestTests" do

end

